# Checkov configuration for Super Linter
#
# CKV_GHA_7 is skipped because this is an educational repository where
# workflow_dispatch inputs are intentionally used to teach GitHub Actions
# concepts. The labs demonstrate how to use inputs for manual workflow triggers.
#
# WARNING: In a production setting, you would NOT skip this check. CKV_GHA_7
# protects against supply chain attacks where user-provided inputs could
# potentially be used to inject malicious code or modify build outputs.

skip-check:
  - CKV_GHA_7
