self-hosted-runner:
  labels:
    - self-hosted-linux

# Ignore 'models' permission scope error - this is a new GitHub permission
# for AI inference that actionlint doesn't recognize yet
ignore:
  - 'permission scope .models.'
